name: Docker Build and Push Nightly

on:
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

  schedule:
    - cron:  '55 5 * * *'

env:
  DOCKER_USER: sumizadocker

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3

    - name: log into docker
      run: |
        docker logout
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u $DOCKER_USER --password-stdin
  
    - name: build all
      run: |
        docker buildx build  --platform linux/amd64 -f alpine-latest -t $DOCKER_USER/${{ github.event.repository.name }}:latest . --push
        docker buildx build  --platform linux/amd64 -f 3.12-alpine -t $DOCKER_USER/${{ github.event.repository.name }}:3.12-alpine . --push

    - name: log out of docker
      run: docker logout
